version: '3.8'

services:

  web:
    build: .
    container_name: natillera_web
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://natillera_user:natillera_password@db:5432/natillera_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    networks:
      - natillera_network

volumes:
  postgres_data:

networks:
  natillera_network:
    driver: bridge
